stages:
  - build
  - test

make:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 ..
    - make ursadb_test
run_tests:
  stage: test
  dependencies:
    - make
  script:
    - ./build/ursadb_test
