stages:
  - build
  - test

make:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build
    - cmake --build build/ --target ursadb_test -- -j 4
run_tests:
  stage: test
  dependencies:
    - make
  script:
    - ./build/ursadb_test
