stages:
  - build
  - test

make:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build
    - cmake ..
    - make ursadb_test
run_tests:
  stage: test
  dependencies:
    - make
  script:
    - ./build/ursadb_test
