stages:
  - build
  - test

make:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_C_COMPILER=/usr/bin/clang -D CMAKE_CXX_COMPILER=/usr/bin/clang++ ..
    - make ursadb_test
run_tests:
  stage: test
  dependencies:
    - make
  script:
    - ./build/ursadb_test
