version: '3'
services:
  e2etests:
    build:
      context: .
      dockerfile: e2e-correctness-tests/Dockerfile
    depends_on:
      - "ursadb"
    volumes:
      - "./e2e-state/samples:/mnt/samples"
  ursadb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9281:9281"
    volumes:
      - "./e2e-state/samples:/mnt/samples"
      - "./e2e-state/index:/var/lib/ursadb"

