name: "Code testing"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_clang_format:
    name: test clang format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cpp'
        clangFormatVersion: 9
  run_cmake_build:
    name: run cmake build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/ursadb_test
