name: "Test experimental configurations"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  unittest_querygraphs:
    name: "run unit tests (experiment: querygraphs)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: install dependencies
      run: sudo apt-get install gcc g++ libzmq3-dev cmake build-essential
    - name: configure
      run: mkdir build && cd build && cmake -DEXPERIMENTAL_QUERY_GRAPHS=On ..
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/ursadb_test
  e2etest_querygraphs:
    name: "run e2e tests (experiment: querygraphs)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: install dependencies
      run: sudo apt-get install gcc g++ libzmq3-dev cmake build-essential git python3 python3-pip
    - name: install python dependencies
      run: pip3 install pyzmq pytest
    - name: configure
      run: mkdir build && cd build && cmake -DEXPERIMENTAL_QUERY_GRAPHS=On ..
    - name: build
      run: cd build && make ursadb ursadb_new
    - name: test
      run: env EXPERIMENTAL_QUERY_GRAPHS=On python3 -m pytest
