name: "Code testing"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_python_types:
    name: test clang format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 9
