name: "Code testing"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_clang_format:
    name: test clang format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install gcc g++ libzmq3-dev cmake build-essential git
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: clang-format
      run: cmake --build build --target format
    - name: check formatting
      run: git diff --quiet
  run_cmake_build:
    name: run cmake build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install gcc g++ libzmq3-dev cmake build-essential
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/ursadb_test
